src/AppBundle/Entity/Meeting.php
<?php

namespace AppBundle\Entity;

use DateTime;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Event\PreUpdateEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;
use Swagger\Annotations as SWG;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Meeting
 *
 * @ORM\Table(name="meeting")
 * @ORM\Entity
 */
class Meeting
{

  const STATUS_PENDING = 0;
  const STATUS_APPROVED = 1;
  const STATUS_REFUSED = 2;
  const STATUS_MISSED = 3;
  const STATUS_DONE = 4;
  const STATUS_CANCELLED = 5;
  const STATUS_DRAFT = 6;

  /**
   * @ORM\Column(type="guid")
   * @ORM\Id
   * @SWG\Property(description="Meeting's uuid", type="string")
   */
  private $id;

  /**
 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Calendar")
 * @ORM\JoinColumn(name="calendar_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
 * @Assert\NotBlank(message="Questo campo è obbligatorio (calendar)")
 * @SWG\Property(description="Meeting's calendar id", type="string")
 * @Serializer\Exclude()
 */
  private $calendar;

  /**
   * @ORM\ManyToOne(targetEntity="AppBundle\Entity\OpeningHour", inversedBy="meetings")
   * @ORM\JoinColumn(name="opening_hour_id", referencedColumnName="id", nullable=true)
   * @SWG\Property(description="Meeting's opening hour id", type="string")
   * @Serializer\Exclude()
   */
  private $openingHour;

  /**
   * @var string
   *
   * @ORM\Column(name="email", type="string", length=255, nullable=true)
   * @SWG\Property(description="Meeting's user email", type="string")
   */
  private $email;

  /**
   * @var string
   *
   * @ORM\Column(name="phone_number", type="string", nullable=true)
   * @SWG\Property(description="Meeting's user phone number", type="string")
   */
  private $phoneNumber;

  /**
   * @var string
   *
   * @ORM\Column(name="fiscal_code", type="string", length=16, nullable=true)
   * @SWG\Property(description="Meeting's user fiscal code", type="string")
   */
  private $fiscalCode;

  /**
   * @var string
   *
   * @ORM\Column(name="name", type="string", length=255, nullable=true)
   * @SWG\Property(description="Meeting's user name", type="string", )
   */
  private $name;

  /**
   * @ORM\ManyToOne(targetEntity="AppBundle\Entity\CPSUser")
   * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true)
   * @SWG\Property(description="Meeting's user id", type="string")
   * @Serializer\Exclude()
   */
  private $user;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="from_time", type="datetime")
   * @Assert\NotBlank(message="Questo campo è obbligatorio (from Time)")
   * @SWG\Property(description="Meeting's from Time")
   */
  private $fromTime;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="to_time", type="datetime")
   * @Assert\NotBlank(message="Questo campo è obbligatorio (to Time)")
   * @SWG\Property(description="Meeting's to Time")
   */
  private $toTime;

  /**
   * @var string
   *
   * @ORM\Column(name="user_message", type="text", nullable=true)
   * @SWG\Property(description="Meeting's User Message", type="string")
   */
  private $userMessage;

  /**
   * @var string
   *
   * @ORM\Column(name="motivation_outcome", type="text", nullable=true)
   * @SWG\Property(description="Meeting's Operator Message", type="string")
   */
  private $motivationOutcome;

  /**
   * @var string
   *
   * @ORM\Column(name="videoconference_link", type="string", nullable=true)
   * @Assert\Url(message="url non valido (videoconferenceLink)")
   * @SWG\Property(description="Meeting's videoconference link", type="string")
   */
  private $videoconferenceLink;

  /**
   * @ORM\Column(type="integer")
   * @Assert\NotBlank(message="Seleziona un'opzione. Lo stato è un parametro obbligatorio")
   * @Assert\NotNull()
   * @SWG\Property(description="Meeting's status", type="integer")
   */
  private $status;

  /**
   * @ORM\Column(type="integer", nullable=false)
   * @SWG\Property(description="Meeting's rescheduled times", type="integer")
   */
  private $rescheduled;

  /**
   * @var string
   *
   * @ORM\Column(name="cancel_link", type="string", length=255, nullable=true)
   * @SWG\Property(description="Meeting's cancel link", type="string")
   * @Serializer\Exclude()
   */
  private $cancelLink;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="draft_expiration", type="datetime", nullable=true)
   * @SWG\Property(description="Meeting draft expiration time")
   */
  private $draftExpiration;

  /**
   * @ORM\Column(type="datetime")
   * @SWG\Property(description="Meeting's creation date")
   */
  private $createdAt;

  /**
   * @ORM\Column(type="datetime")
   * @SWG\Property(description="Meeting's last modified date")
   */
  private $updatedAt;

  /**
   * Meeting constructor.
   * @throws \Exception
   */
  public function __construct()
  {
    if (!$this->id) {
      $this->id = Uuid::uuid4();
      $this->cancelLink = hash('sha256', $this->id . (new DateTime())->format('c'));
    }
  }

  /**
   * get id
   *
   * @return UuidInterface
   */
  public function getId()
  {
    return $this->id;
  }

  /**
   * Get Calendar
   *
   * @return Calendar
   */
  public function getCalendar(): ?Calendar
  {
    return $this->calendar;
  }

  /**
   * Set Calendar
   *
   * @param Calendar $calendar
   * @return $this
   */
  public function setCalendar(?Calendar $calendar): self
  {
    $this->calendar = $calendar;

    return $this;
  }

  /**
   * @Serializer\VirtualProperty(name="calendar")
   * @Serializer\Type("string")
   * @Serializer\SerializedName("calendar")
   */
  public function getCalendarId(): string
  {
    return $this->calendar->getId();
  }

  /**
   * Get OpeningHour
   *
   * @return OpeningHour
   */
  public function getOpeningHour(): ?OpeningHour
  {
    return $this->openingHour;
  }

  /**
   * Set OpeningHour
   *
   * @param OpeningHour $openingHour
   * @return $this
   */
  public function setOpeningHour(?OpeningHour $openingHour): self
  {
    $this->openingHour = $openingHour;

    return $this;
  }

  /**
   * Set email.
   *
   * @param string $email
   *
   * @return Meeting
   */
  public function setEmail($email)
  {
    $this->email = $email;

    return $this;
  }

  /**
   * Get email.
   *
   * @return string|null
   */
  public function getEmail()
  {
    return $this->email;
  }

  /**
   * Set phone number.
   *
   * @param string $phoneNumber
   *
   * @return Meeting
   */
  public function setPhoneNumber($phoneNumber)
  {
    $this->phoneNumber = $phoneNumber;

    return $this;
  }

  /**
   * Get phone number.
   *
   * @return string|null
   */
  public function getPhoneNumber()
  {
    return $this->phoneNumber;
  }

  /**
   * Set user Fiscal Code.
   *
   * @param string $fiscal_code
   *
   * @return Meeting
   */
  public function setFiscalCode($fiscal_code)
  {
    $this->fiscalCode = $fiscal_code;

    return $this;
  }

  /**
   * Get fiscal code.
   *
   * @return string|null
   */
  public function getFiscalCode()
  {
    return $this->fiscalCode;
  }

  /**
   * Set user Name.
   *
   * @param string $name
   *
   * @return Meeting
   */
  public function setName($name)
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Get name.
   *
   * @return string|null
   */
  public function getName()
  {
    return $this->name;
  }

  /**
   * Get Owner
   *
   * @return CPSUser|null
   */
  public function getUser(): ?CPSUser
  {
    return $this->user;
  }

  /**
   * Get Owner
   *
   * @param CPSUser|null $user
   * @return $this
   */
  public function setUser(?CPSUser $user): self
  {
    if ($user)
      $this->user = $user;

    return $this;
  }

  /**
   * @Serializer\VirtualProperty(name="user")
   * @Serializer\Type("string")
   * @Serializer\SerializedName("user")
   * @Serializer\Exclude(if="!object.getUser()")
   */
  public function getUserId(): ?string
  {
    if ($this->user)
      return $this->user->getId();
    else return null;
  }

  /**
   * Set fromTime.
   *
   * @param \DateTime $fromTime
   *
   * @return Meeting
   */
  public function setFromTime($fromTime)
  {
    $this->fromTime = $fromTime;

    return $this;
  }

  /**
   * Get fromTime.
   *
   * @return \DateTime
   */
  public function getFromTime()
  {
    return $this->fromTime;
  }

  /**
   * Set toTime.
   *
   * @param \DateTime $toTime
   *
   * @return Meeting
   */
  public function setToTime($toTime)
  {
    $this->toTime = $toTime;

    return $this;
  }

  /**
   * Get toTime.
   *
   * @return \DateTime
   */
  public function getToTime()
  {
    return $this->toTime;
  }

  /**
   * Get status
   *
   * @return mixed
   */
  public function getStatus()
  {
    return $this->status;
  }

  public function getStatusName()
  {
    switch ($this->status) {
      case 0:
        return 'In attesa di conferma';
        break;
      case 1:
        return 'Approvato';
        break;
      case 2:
        return 'Rifiutato';
        break;
      case 3:
        return 'Assente';
        break;
      case 4:
        return 'Concluso';
        break;
      case 5:
        return 'Annullato';
        break;
      case 6:
        return 'Bozza';
        break;
      default:
        return 'Errore';
    }
  }

  /**
   * Set status
   *
   * @param $status
   *
   * @return $this
   */
  public function setStatus($status)
  {
    $this->status = $status;

    return $this;
  }

  /**
   * Set userMessage.
   *
   * @param string $userMessage
   *
   * @return Meeting
   */
  public function setUserMessage($userMessage)
  {
    $this->userMessage = $userMessage;

    return $this;
  }

  /**
   * Get userMessage.
   *
   * @return string
   */
  public function getUserMessage()
  {
    return $this->userMessage;
  }

  /**
   * Set motivationOutcome.
   *
   * @param string $motivationOutcome
   *
   * @return Meeting
   */
  public function setMotivationOutcome($motivationOutcome)
  {

src/AppBundle/Form/TagsType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class TagsType extends AbstractType {

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder->addViewTransformer(new CallbackTransformer(
      function ($original) {
        return $original ? implode(', ', $original) : '';
      },
      function ($submitted) {
        if (!$submitted) {
          return [];
        }

        $submitted = array_map(function($tag) {
          return trim($tag);
        }, explode(',', $submitted));

        return $submitted;
      }
    ));
  }

  public function getName()
  {
    return 'tags';
  }

  public function getParent()
  {
    return TextType::class;
  }


}

src/AppBundle/Resources/views/Operatori/parts/allegati.html.twig
<!-- MODULO COMPILATO -->
{% if pratica.moduliCompilati|length > 0 %}
    <h6 class="primary-color">{{ 'operatori.scarica' | trans }}</h6>
    <div class="row align-items-center text-center mt-3 mb-5">
        <div class="col-2">
            <i class="fa fa-2x fa-file-pdf-o"></i>
        </div>
        <div class="col-6 text-truncate">
            {{ pratica.moduliCompilati[0].originalFilename }}
        </div>
        <div class="col-2">
            {{ pratica.moduliCompilati[0].getHumanReadableFileSize }}
        </div>
        <div class="col-2">
            <a href="{{ path('allegati_download_operatore', {'allegato': pratica.moduliCompilati[0]}) }}" download>
                <svg class="icon icon-primary">
                    <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-download"></use>
                </svg>
            </a>
        </div>
    </div>
{% else %}
    <a class="list-item disabled" href="#">
        <svg class="icon icon-sm">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-file"></use>
        </svg>
        {{ 'operatori.scarica' | trans }}
    </a>
{% endif %}

    {# @var allegato \AppBundle\Entity\Allegato #}
<!-- ALLEGATI PRATICA -->
{% if pratica.allegati.count > 0 %}
    <h6 class="primary-color">{{ 'operatori.allegati_modulo' | trans }}</h6>
    {% for allegato in pratica.allegati %}
        <div class="row align-items-center text-center mt-3 mb-5">
            <div class="col-2">
                {% if allegato.file.extension == 'pdf' or allegato.file.extension == 'p7m' %}
                    <i class="fa fa-2x fa-file-pdf-o"></i>
                {% else %}
                    <i class="fa fa-2x fa-file-o"></i>
                {% endif %}
            </div>
            <div class="col-6 text-truncate">
                {{ allegato.originalFilename }}
            </div>
            <div class="col-2">
                {{ allegato.getHumanReadableFileSize }}
            </div>
            <div class="col-2">
                <a href="{{ path('allegati_download_operatore', {'allegato': allegato}) }}" download>
                    <svg class="icon icon-primary">
                        <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-download"></use>
                    </svg>
                </a>
            </div>
        </div>
    {% endfor %}
{% endif %}
<!-- ALLEGATI MESSAGGI -->
{% if messageAttachments|length > 0 %}
    <h6 class="primary-color">{{ 'operatori.allegati_messaggi' | trans }}</h6>
    {% for allegato in messageAttachments %}
        <div class="row align-items-center text-center mt-3 mb-5">
            <div class="col-2">
                {% if allegato.file.extension == 'pdf' or allegato.file.extension == 'p7m' %}
                    <i class="fa fa-2x fa-file-pdf-o"></i>
                {% else %}
                    <i class="fa fa-2x fa-file-o"></i>
                {% endif %}
            </div>
            <div class="col-6 text-truncate">
                {{ allegato.originalFilename }}
            </div>
            <div class="col-2">
                {{ allegato.getHumanReadableFileSize }}
            </div>
            <div class="col-2">
                <a href="{{ path('allegati_download_operatore', {'allegato': allegato}) }}" download>
                    <svg class="icon icon-primary">
                        <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-download"></use>
                    </svg>
                </a>
            </div>
        </div>
    {% endfor %}
{% endif %}

<!-- RISPOSTA OPERATORE -->
{% if pratica.statusName == 'STATUS_COMPLETE' or pratica.statusName == 'STATUS_CANCELLED' %}
    {% if pratica.rispostaOperatore %}
        <h6 class="primary-color">{{ 'operatori.scarica_risposta_firmata'|trans }}</h6>
        <div class="row align-items-center text-center mt-3 mb-5">
            <div class="col-2">
                <i class="fa fa-2x fa-file-pdf-o"></i>
            </div>
            <div class="col-6 text-truncate">
                {{ pratica.rispostaOperatore.originalFilename }}
            </div>
            <div class="col-2">
                {{ pratica.rispostaOperatore.getHumanReadableFileSize }}
            </div>
            <div class="col-2">
                <a href="{{ path('risposta_download_operatore', {'allegato': pratica.rispostaOperatore.id}) }}" download>
                    <svg class="icon icon-primary">
                        <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-download"></use>
                    </svg>
                </a>
            </div>
        </div>
    {% endif %}
{% endif %}

src/AppBundle/Resources/views/Operatori/parts/approva_o_rigetta.html.twig
{% if pratica.canBeAssigned %}
  <div class="row mb-5">
    {% if not pratica.servizio.praticaFlowOperatoreServiceName or pratica.servizio.praticaFlowOperatoreServiceName == 'ocsdc.form.flow.standardoperatore' %}

      {% if  pratica.status == constant('STATUS_REQUEST_INTEGRATION', pratica) %}
        <div class="col d-flex justify-content-center">
          <p>Richiesta integrazioni in attesa di protocollazione</p>
        </div>
      {% elseif  pratica.status == constant('STATUS_SUBMITTED_AFTER_INTEGRATION', pratica) %}
        <div class="col d-flex justify-content-center">
          <p>Integrazioni in attesa di protocollazione</p>
        </div>
      {% elseif  pratica.status == constant('STATUS_DRAFT_FOR_INTEGRATION', pratica) %}
        <div class="col d-flex justify-content-center">
          <a href="{{ path('operatori_accept_integration', {'pratica': pratica}) }}" class="btn btn-primary">
            <svg class="icon icon-light">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-check"></use>
            </svg>
            {{ 'operatori.chiudi_richiesta_integrazione' | trans }}
          </a>
        </div>
      {% elseif pratica.status == constant('STATUS_PENDING', pratica) %}
        {{ include('@App/Operatori/parts/change_status_modal.html.twig') }}
        <div class="col d-flex justify-content-center">
          <button class="btn btn-outline-secondary" id="modal_refuse" data-toggle="modal"
                  data-target=".bd-example-modal-lg">
            <svg class="icon icon-danger">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
            </svg>{{ 'operatori.rigetta' | trans }}
          </button>
        </div>

        {% if feature('feature_integration_request') %}
          <div class="col d-flex justify-content-center">
            <button class="btn btn-outline-secondary" id="modal-integration" data-toggle="modal"
                    data-target="#integration-request-modal">
              <svg class="icon icon-warning">
                <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-comment"></use>
              </svg>{{ 'operatori.richiedi_intergrazioni' | trans }}</button>
          </div>
        {% endif %}

        <div class="col d-flex justify-content-center">
          <button class="btn btn-primary" id="modal_approve" data-toggle="modal"
                  data-target=".bd-example-modal-lg">
            <svg class="icon icon-light">
              <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-check"></use>
            </svg>{{ 'operatori.approva' | trans }}</button>
        </div>
      {% endif %}


    {% else %}
      <div class="col-6 d-flex justify-content-center">
        <a href="{{ path('operatori_elabora_pratica', {'pratica': pratica}) }}" class="btn btn-secondary">
          <svg class="icon icon-light">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-close"></use>
          </svg>
          {{ 'operatori.rigetta' | trans }}
        </a>
      </div>
      <div class="col-6 d-flex justify-content-center">
        <a href="{{ path('operatori_elabora_pratica', {'pratica': pratica}) }}" class="btn btn-primary">
          <svg class="icon icon-light">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-check"></use>
          </svg>
          {{ 'operatori.approva' | trans }}
        </a>
      </div>
    {% endif %}
  </div>
{% else %}
  <div class=" alert alert-info mb-4">
    <p>
      {{ 'operatori.iter_completato' | trans({
        '%statusName%': pratica.statusName | trans,
        '%data%': pratica.latestStatusChangeTimestamp | date(ocsdc_default_date_format),
        '%ore%': pratica.latestStatusChangeTimestamp | date('H:i:s')})
      | raw }}
    </p>
    {% if pratica.motivazioneEsito %}
      <p class="mb-0 p-2 bg-light">{{ pratica.motivazioneEsito | striptags }}</p>
    {% endif %}
    {% if pratica.allegatiOperatore|length > 0 %}
      <p class="mb-0 px-2 pb-2 bg-light">
        {% for allegato in pratica.allegatiOperatore %}
          <a class="text-decoration-none d-block"
             href="{{ path('allegati_download_operatore', {'allegato': allegato.id}) }}">
            <small><i class="fa fa-file"></i> {{ allegato.description }}</small>
          </a>
        {% endfor %}
      </p>
    {% endif %}
  </div>
{% endif %}

src/AppBundle/Resources/views/Operatori/parts/azioni_operatore.html.twig
<hr />
<div class="row">
    <div class="col-md-12 text-center">
        <a href="{{ path('operatori_elabora_pratica', {'pratica': pratica}) }}"
           class="btn btn-primary btn-lg">
            {{ 'operatori.elabora'|trans }}
        </a>
    </div>
</div>

src/AppBundle/Resources/views/Operatori/parts/change_status_modal.html.twig
<style>
  .modal .form-group {
    margin-bottom: 0;
    padding-bottom: 0;
  }
</style>

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
     aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="p-4">
        <div class="row">
          <div class="col-lg-12 px-lg-4 py-lg-2">
            <h1 id="modalTitle"></h1>
            <p>Verrà inviato un messaggio all’indirizzo dell’utente <a
                href="mailto:{{ pratica.user.emailContatto }}">{{ pratica.user.emailContatto }}</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 px-lg-4 py-lg-2">
            {{ form_start(outcomeForm) }}
            <div class="d-none">{{ form_row(outcomeForm.outcome) }}</div>
            {{ form_row(outcomeForm.message) }}
            <small
              class="form-text text-muted mb-3">{{ 'operatori.flow.approva_o_rigetta.motivazione.esito_help' | trans }}</small>
            <div class="form-group">
              <label>{{ 'operatori.flow.approva_o_rigetta.motivazione.allega_label' | trans }}</label>
              {{ form_row(outcomeForm.attachments) }}
            </div>
            <div id="vueApp" class="px-2">
              {% if outcomeForm.vars.helper.vueApp %}
              <{{ outcomeForm.vars.helper.vueApp }} id="upload_outcome_attachment">
            </{{ outcomeForm.vars.helper.vueApp }}>
            {% endif %}
            <small class="form-text text-muted mb-3">{{ 'operatori.flow.approva_o_rigetta.motivazione.allega_help' | trans }}</small>
            {% if outcomeForm.payment_amount is defined  %}
              {{ form_row(outcomeForm.payment_amount) }}
              <small class="form-text text-muted mb-3">{{ 'operatori.flow.approva_o_rigetta.motivazione.payment_amount_help' | trans }}</small>
            {% endif %}
          </div>
          <div class="row justify-content-between mt-3">
            <div class="col-auto align-self-center">
              <strong>
                <svg class="icon icon-sm">
                  <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-warning-circle"></use>
                </svg>
                Una volta elaborata la pratica non sarà più possibile effettuare modifiche
              </strong>
            </div>
            <div class="col-auto">
              <button type="submit" class="btn btn-primary float-right">{{ 'messaggi.invia' | trans }}</button>
            </div>
          </div>
          {{ form_rest(outcomeForm) }}

          {{ form_end(outcomeForm) }}
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<div class="modal fade" id="integration-request-modal" tabindex="-1" role="dialog"
     aria-labelledby="IntegrationRequestModal" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="p-4">
        <div class="row">
          <div class="col-lg-12 px-lg-4 py-lg-2">
            <h1>Richiedi integrazione</h1>
            <p>Verrà inviato un messaggio all’indirizzo dell’utente <a
                href="mailto:{{ pratica.user.emailContatto }}">{{ pratica.user.emailContatto }}</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12 px-lg-4 py-lg-2">
            {{ form_start(integration_request_form) }}
            {{ form_row(integration_request_form.message) }}
            <small class="form-text text-muted mb-3">
              Utilizza questo campo per motivare la richiesta di integrazione.<br />
              Una volta inviato l'utente riceverà un messaggio con il testo specificato, sarà possibile verificare eventuali
              risposte nella sezione messaggi.
            </small>

            <div class="row justify-content-between mt-3">
              <div class="col-auto">
                <button type="submit" class="btn btn-primary float-right">Invia richiesta integrazione</button>
              </div>
            </div>
            {{ form_rest(integration_request_form) }}

            {{ form_end(integration_request_form) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

src/AppBundle/Resources/views/Operatori/parts/commenti.html.twig
<div class="row">
  <div class="col-md-12">
    <ul class="list-unstyled">
      {% for commento in pratica.commenti %}
        <li>
          <small>{{ commento.createdAt|date(ocsdc_default_datetime_format) }}</small>
          <p><strong>{{ commento.creator }}:</strong> {{ commento.text }}</p>
        </li>
      {% endfor %}
    </ul>
    {{ form(messageForm) }}
  </div>
</div>

src/AppBundle/Resources/views/Operatori/parts/fascicolo_pratica.html.twig
<a class="list-item large medium left-icon icon-left pr-0{% if pratica.id == reference.id %} pb-2 bg-100{% endif %}"
   {% if pratica.servizio.id in user.serviziAbilitati %}href="{{ path('operatori_show_pratica', {'pratica': pratica }) }}"{% else %}href="#" style="cursor: not-allowed" title="Non hai i permessi per visualizzare questa pratica" {% endif %}>

  <span style="line-height: 1.5">{{ pratica.servizio.name }}</span>
  <svg class="icon icon-primary icon-left mt-2 pr-1">
    <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-{% if pratica.id == reference.id %}arrow-right{% else %}file{% endif %}"></use>
  </svg>
  <p class="m-0">
    acquisita il {{ pratica.submissionTime | date('d/m/Y H:i:s') }} <span class="badge badge-light text-decoration-none">{{ pratica.statusName | trans }}</span>
  </p>
</a>
{% if pratica.children.count > 0 %}
  <li><span class="divider"></span>
  <ul class="link-sublist">
    {% for item in pratica.children %}
      <li>{{ include('@App/Operatori/parts/fascicolo_pratica.html.twig', {'pratica': item, 'reference': reference}) }}</li>
      {% if not loop.last %}<li><span class="divider"></span>{% endif %}
    {% endfor %}
  </ul>
{% endif %}

src/AppBundle/Resources/views/Operatori/parts/pratiche_recenti.html.twig
<div class="link-list-wrapper multiline">
  <ul class="link-list">
    {% for pratica_recente  in pratiche_recenti %}
      <li>
        <a class="list-item large medium left-icon icon-left pr-0"
           href="{% if pratica_recente.servizio.id in user.serviziAbilitati %}{{ path('operatori_show_pratica', {'pratica': pratica_recente }) }}{% else %}#{% endif %}">
          <span style="line-height: 1.5">{{ pratica_recente.servizio.name }}</span>
          <svg class="icon icon-primary icon-left mt-2 pr-1">
            <use xlink:href="/bootstrap-italia/dist/svg/sprite.svg#it-file"></use>
          </svg>
          <p class="m-0">
            acquisita il {{ pratica_recente.submissionTime | date('d/m/Y H:i:s') }} <span class="badge badge-light text-decoration-none">{{ pratica_recente.statusName | trans }}</span>
          </p>
        </a>
      </li>
    {% if not loop.last %}<li><span class="divider"></span>{% endif %}
    {% endfor %}
  </ul>
</div>